version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tinyrpg
    volumes:
      - ./app:/app
    networks:
      - tinyrpg-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tinyrpg
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tinyrpg-network

volumes:
  postgres_data:

networks:
  tinyrpg-network:
    driver: bridge 